In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import pandas as pd


**Read the dataset**

In [3]:
train_dataset=pd.read_csv("/content/drive/MyDrive/ML_TRAINING/Dataset/Train.csv")

In [4]:
train_dataset.head(10)

Item_Identifier  Item_Weight  ...        Outlet_Type  Item_Outlet_Sales
0           FDA15        9.300  ...  Supermarket Type1          3735.1380
1           DRC01        5.920  ...  Supermarket Type2           443.4228
2           FDN15       17.500  ...  Supermarket Type1          2097.2700
3           FDX07       19.200  ...      Grocery Store           732.3800
4           NCD19        8.930  ...  Supermarket Type1           994.7052
5           FDP36       10.395  ...  Supermarket Type2           556.6088
6           FDO10       13.650  ...  Supermarket Type1           343.5528
7           FDP10          NaN  ...  Supermarket Type3          4022.7636
8           FDH17       16.200  ...  Supermarket Type1          1076.5986
9           FDU28       19.200  ...  Supermarket Type1          4710.5350

[10 rows x 12 columns]

**Checking Null values**

In [5]:
train_dataset.isnull().any()

Item_Identifier              False
Item_Weight                   True
Item_Fat_Content             False
Item_Visibility              False
Item_Type                    False
Item_MRP                     False
Outlet_Identifier            False
Outlet_Establishment_Year    False
Outlet_Size                   True
Outlet_Location_Type         False
Outlet_Type                  False
Item_Outlet_Sales            False
dtype: bool

In [6]:
train_dataset.isnull().sum()


Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [7]:
train_dataset["Item_Type"].unique()

array(['Dairy', 'Soft Drinks', 'Meat', 'Fruits and Vegetables',
       'Household', 'Baking Goods', 'Snack Foods', 'Frozen Foods',
       'Breakfast', 'Health and Hygiene', 'Hard Drinks', 'Canned',
       'Breads', 'Starchy Foods', 'Others', 'Seafood'], dtype=object)

In [8]:
train_dataset["Item_Fat_Content"].unique()

array(['Low Fat', 'Regular', 'low fat', 'LF', 'reg'], dtype=object)

In [9]:
train_dataset["Outlet_Size"].unique()

array(['Medium', nan, 'High', 'Small'], dtype=object)

In [10]:
train_dataset["Outlet_Type"].unique()

array(['Supermarket Type1', 'Supermarket Type2', 'Grocery Store',
       'Supermarket Type3'], dtype=object)

**Replacing duplicates Values**

In [11]:
train_dataset["Item_Fat_Content"]=train_dataset["Item_Fat_Content"].replace(to_replace='Low Fat', value='LF')
train_dataset["Item_Fat_Content"].unique()

array(['LF', 'Regular', 'low fat', 'reg'], dtype=object)

In [12]:
train_dataset["Item_Fat_Content"]=train_dataset["Item_Fat_Content"].replace(to_replace='low fat', value='LF')
train_dataset["Item_Fat_Content"].unique()

array(['LF', 'Regular', 'reg'], dtype=object)

In [13]:
train_dataset["Item_Fat_Content"]=train_dataset["Item_Fat_Content"].replace(to_replace='reg', value='Regular')
train_dataset["Item_Fat_Content"].unique()

array(['LF', 'Regular'], dtype=object)

**Replacing Null Values**

In [14]:
train_dataset["Item_Weight"].fillna(train_dataset['Item_Weight'].mean(), inplace=True)

In [15]:
print("Outlet_Size_mode ",train_dataset["Outlet_Size"].mode()[0])

Outlet_Size_mode  Medium


In [16]:
train_dataset['Outlet_Size'].fillna(train_dataset['Outlet_Size'].mode()[0],inplace=True)

In [17]:
train_dataset.isnull().any()

Item_Identifier              False
Item_Weight                  False
Item_Fat_Content             False
Item_Visibility              False
Item_Type                    False
Item_MRP                     False
Outlet_Identifier            False
Outlet_Establishment_Year    False
Outlet_Size                  False
Outlet_Location_Type         False
Outlet_Type                  False
Item_Outlet_Sales            False
dtype: bool

In [18]:
train_dataset.columns

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Item_Outlet_Sales'],
      dtype='object')

**Splitting X and Y**

In [19]:
x=train_dataset.iloc[:,1:11].values
y=train_dataset.iloc[:,11:12].values

In [20]:
x[0:5]

array([[9.3, 'LF', 0.016047301, 'Dairy', 249.8092, 'OUT049', 1999,
        'Medium', 'Tier 1', 'Supermarket Type1'],
       [5.92, 'Regular', 0.019278216, 'Soft Drinks', 48.2692, 'OUT018',
        2009, 'Medium', 'Tier 3', 'Supermarket Type2'],
       [17.5, 'LF', 0.016760075, 'Meat', 141.618, 'OUT049', 1999,
        'Medium', 'Tier 1', 'Supermarket Type1'],
       [19.2, 'Regular', 0.0, 'Fruits and Vegetables', 182.095, 'OUT010',
        1998, 'Medium', 'Tier 3', 'Grocery Store'],
       [8.93, 'LF', 0.0, 'Household', 53.8614, 'OUT013', 1987, 'High',
        'Tier 3', 'Supermarket Type1']], dtype=object)

In [21]:
x.shape

(8523, 10)

In [22]:
y.shape

(8523, 1)

**Converting Categorical values to numerical values**

In [23]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


In [24]:
ct = ColumnTransformer([("one",OneHotEncoder(),[1,3,5,7,8,9])],remainder = "passthrough")
x = ct.fit_transform(x)

In [25]:
x

<8523x42 sparse matrix of type '<class 'numpy.float64'>'
	with 84704 stored elements in Compressed Sparse Row format>

In [26]:
type(x)

scipy.sparse.csr.csr_matrix

In [27]:
x=x.toarray()

In [28]:
x

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.60473010e-02, 2.49809200e+02, 1.99900000e+03],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, ...,
        1.92782160e-02, 4.82692000e+01, 2.00900000e+03],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.67600750e-02, 1.41618000e+02, 1.99900000e+03],
       ...,
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        3.51862710e-02, 8.51224000e+01, 2.00400000e+03],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, ...,
        1.45220646e-01, 1.03133200e+02, 2.00900000e+03],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        4.48782800e-02, 7.54670000e+01, 1.99700000e+03]])

In [29]:
#Sparce matrix=less space
#array=consume more space

In [30]:
y

array([[3735.138 ],
       [ 443.4228],
       [2097.27  ],
       ...,
       [1193.1136],
       [1845.5976],
       [ 765.67  ]])

**splitting dataset into train set and test set**

In [31]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state = 0)

In [32]:
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [33]:
y_pred = mlr.predict(x_test)

In [34]:
y_pred

array([[ 2450.47347974],
       [ 2536.85851504],
       [ 2209.2944831 ],
       ...,
       [ 4261.94385727],
       [-1058.0538482 ],
       [ 5417.45093856]])

In [35]:
y_pred.shape

(1705, 1)

In [36]:
y_pred[0:1705]

array([[ 2450.47347974],
       [ 2536.85851504],
       [ 2209.2944831 ],
       ...,
       [ 4261.94385727],
       [-1058.0538482 ],
       [ 5417.45093856]])

In [37]:
y_test

array([[1426.1436],
       [1201.769 ],
       [1836.2764],
       ...,
       [2885.5772],
       [ 218.3824],
       [5478.2024]])

In [38]:
from sklearn.metrics import r2_score
accuracy = r2_score(y_pred,y_test)

In [39]:
accuracy

0.21021207790222418